import type { CapabilityManifest, CapabilityPermission } from "@railwise/sdk/v2"

const none: CapabilityPermission = {
  filesystem: "none",
  network: false,
  shell: false,
  external_directory: false,
  secrets: false,
}

const read: CapabilityPermission = {
  ...none,
  filesystem: "read",
}

const write: CapabilityPermission = {
  ...read,
  filesystem: "write",
}

const network: CapabilityPermission = {
  ...none,
  network: true,
  secrets: true,
}

const external: CapabilityPermission = {
  ...write,
  external_directory: true,
}

export const starterCapabilities: CapabilityManifest[] = [
  {
    id: "railwise.harness.safe",
    kind: "harness_profile",
    name: "本地安全模式",
    description: "默认要求用户确认写文件、执行命令和访问外部目录。",
    version: "0.1.0",
    source: "builtin",
    enabled: true,
    installed: true,
    permissions: read,
    tags: ["安全", "默认", "Harness"],
  },
  {
    id: "railwise.harness.delivery",
    kind: "harness_profile",
    name: "交付审查模式",
    description: "面向成果交付的 Harness 配置，强调权限留痕、质量闸门和报告归档。",
    version: "0.1.0",
    source: "builtin",
    enabled: false,
    installed: true,
    permissions: write,
    tags: ["Harness", "交付", "审查"],
  },
  {
    id: "railwise.agent.chief_manager",
    kind: "agent",
    name: "项目总控",
    description: "理解任务、拆解计划，并调度专业智能体执行。",
    version: "0.1.0",
    source: "builtin",
    enabled: true,
    installed: true,
    permissions: read,
    tags: ["主控", "调度"],
  },
  {
    id: "railwise.agent.source_ingestor",
    kind: "agent",
    name: "资料入库专员",
    description: "整理外部规范、项目资料和原始文件，准备 Wiki 入库上下文。",
    version: "0.1.0",
    source: "builtin",
    enabled: true,
    installed: true,
    permissions: write,
    tags: ["资料", "入库"],
  },
  {
    id: "railwise.agent.norm_librarian",
    kind: "agent",
    name: "规范资料管理员",
    description: "查询工程测量规范，返回可追溯条文和引用依据。",
    version: "0.1.0",
    source: "builtin",
    enabled: true,
    installed: true,
    permissions: read,
    tags: ["规范", "引用"],
  },
  {
    id: "railwise.agent.knowledge_curator",
    kind: "agent",
    name: "知识库维护员",
    description: "把项目经验、规范条文和审查记录沉淀为可检索 Wiki。",
    version: "0.1.0",
    source: "builtin",
    enabled: true,
    installed: true,
    permissions: write,
    tags: ["Wiki", "知识库"],
  },
  {
    id: "railwise.agent.cpiii_specialist",
    kind: "agent",
    name: "CPIII 测量专家",
    description: "负责 CPIII 控制网、轨道精调和测量成果复核。",
    version: "0.1.0",
    source: "builtin",
    enabled: true,
    installed: true,
    permissions: read,
    tags: ["测量", "CPIII"],
  },
  {
    id: "railwise.agent.adjustment_computer",
    kind: "agent",
    name: "平差计算员",
    description: "调用确定性平差工具，输出残差、精度统计和质量标记。",
    version: "0.1.0",
    source: "builtin",
    enabled: true,
    installed: true,
    permissions: write,
    tags: ["平差", "计算"],
  },
  {
    id: "railwise.agent.railway_norm_consultant",
    kind: "agent",
    name: "铁路规范顾问",
    description: "对比铁路测量规范版本，生成可进入报告的合规说明。",
    version: "0.1.0",
    source: "builtin",
    enabled: true,
    installed: true,
    permissions: read,
    tags: ["铁路", "规范"],
  },
  {
    id: "railwise.agent.technical_writer",
    kind: "agent",
    name: "技术报告编写员",
    description: "根据审查结果、计算输出和规范引用生成中文技术报告。",
    version: "0.1.0",
    source: "builtin",
    enabled: true,
    installed: true,
    permissions: write,
    tags: ["报告", "中文写作"],
  },
  {
    id: "railwise.agent.qa_reviewer",
    kind: "agent",
    name: "质量审查员",
    description: "检查成果完整性、风险项、术语一致性和交付前质量闸门。",
    version: "0.1.0",
    source: "builtin",
    enabled: true,
    installed: true,
    permissions: read,
    tags: ["质检", "交付"],
  },
  {
    id: "railwise.agent.data_analyst",
    kind: "agent",
    name: "监测数据分析师",
    description: "整理监测与测量数据，识别趋势、异常和统计摘要。",
    version: "0.1.0",
    source: "builtin",
    enabled: true,
    installed: true,
    permissions: read,
    tags: ["监测", "数据分析"],
  },
  {
    id: "railwise.skill.survey_review",
    kind: "skill",
    name: "复测资料检查",
    description: "检查线路复测资料完整性、缺失文件和交付风险。",
    version: "0.1.0",
    source: "builtin",
    enabled: true,
    installed: true,
    permissions: read,
    tags: ["测绘", "资料检查"],
  },
  {
    id: "railwise.skill.data_analysis",
    kind: "skill",
    name: "测绘数据平差与变形分析",
    description: "把观测数据转换为显式计算输入，并组织平差、粗差探测和结果解释。",
    version: "0.1.0",
    source: "builtin",
    enabled: true,
    installed: true,
    permissions: write,
    tags: ["平差", "数据分析"],
  },
  {
    id: "railwise.skill.standard_reference",
    kind: "skill",
    name: "规范条文速查",
    description: "围绕规范条文查询、引用、版本差异和报告用语进行约束。",
    version: "0.1.0",
    source: "builtin",
    enabled: true,
    installed: true,
    permissions: read,
    tags: ["规范", "引用"],
  },
  {
    id: "railwise.skill.report_delivery",
    kind: "skill",
    name: "成果报告交付",
    description: "整理检查结果、技术说明、交付清单和报告草稿。",
    version: "0.1.0",
    source: "builtin",
    enabled: true,
    installed: true,
    permissions: write,
    tags: ["报告", "交付"],
  },
  {
    id: "railwise.skill.monitoring_design",
    kind: "skill",
    name: "监测方案设计",
    description: "面向基坑、轨道交通保护区和既有线监测方案的结构化编制流程。",
    version: "0.1.0",
    source: "builtin",
    enabled: true,
    installed: true,
    permissions: write,
    tags: ["监测", "方案"],
  },
  {
    id: "railwise.skill.office_exports",
    kind: "skill",
    name: "Word / Excel 成果整理",
    description: "把审查表、统计表和报告内容整理为可交付 Office 文件。",
    version: "0.1.0",
    source: "builtin",
    enabled: true,
    installed: true,
    permissions: write,
    tags: ["Office", "交付"],
  },
  {
    id: "railwise.tool.file_reader",
    kind: "tool",
    name: "本地文件读取",
    description: "读取当前工作区内的工程文件。",
    version: "0.1.0",
    source: "builtin",
    enabled: true,
    installed: true,
    permissions: read,
    tags: ["文件", "本地"],
  },
  {
    id: "railwise.tool.format_converter",
    kind: "tool",
    name: "测量格式转换",
    description: "解析 COSA、NASEW、平差易、Leica、Trimble 等观测数据格式。",
    version: "0.1.0",
    source: "builtin",
    enabled: true,
    installed: true,
    permissions: read,
    tags: ["格式", "测量"],
  },
  {
    id: "railwise.tool.adjustment_indirect",
    kind: "tool",
    name: "间接平差计算",
    description: "运行确定性间接平差，返回未知数、残差、权中误差和精度统计。",
    version: "0.1.0",
    source: "builtin",
    enabled: true,
    installed: true,
    permissions: write,
    tags: ["平差", "计算"],
  },
  {
    id: "railwise.tool.adjustment_robust",
    kind: "tool",
    name: "稳健平差与粗差探测",
    description: "进行粗差探测、稳健平差和观测质量标记。",
    version: "0.1.0",
    source: "builtin",
    enabled: true,
    installed: true,
    permissions: write,
    tags: ["粗差", "质量"],
  },
  {
    id: "railwise.tool.wiki_query",
    kind: "tool",
    name: "规范 Wiki 查询",
    description: "检索已入库规范页面，并返回可引用证据。",
    version: "0.1.0",
    source: "builtin",
    enabled: true,
    installed: true,
    permissions: read,
    tags: ["Wiki", "规范"],
  },
  {
    id: "railwise.tool.report_writer",
    kind: "tool",
    name: "报告文件生成",
    description: "在当前工作区生成 Markdown、清单和报告草稿。",
    version: "0.1.0",
    source: "builtin",
    enabled: true,
    installed: true,
    permissions: write,
    tags: ["文件", "报告"],
  },
  {
    id: "railwise.workflow.survey_package_review",
    kind: "workflow",
    name: "复测资料完整性检查",
    description: "从资料目录出发，检查原始数据、成果文件、缺失项和下一步计划。",
    version: "0.1.0",
    source: "builtin",
    enabled: true,
    installed: true,
    permissions: read,
    tags: ["工作流", "复测"],
  },
  {
    id: "railwise.workflow.norm_wiki_ingestion",
    kind: "workflow",
    name: "规范 Wiki 入库",
    description: "把外部规范资料转换、审查、索引为后续报告可引用的 Wiki 页面。",
    version: "0.1.0",
    source: "builtin",
    enabled: true,
    installed: true,
    permissions: write,
    tags: ["工作流", "规范"],
  },
  {
    id: "railwise.provider.deepseek",
    kind: "provider",
    name: "DeepSeek",
    description: "推荐默认模型提供方，可用于主控和专业智能体。",
    version: "0.1.0",
    source: "builtin",
    enabled: false,
    installed: true,
    permissions: network,
    tags: ["模型", "推荐"],
  },
  {
    id: "railwise.provider.openrouter",
    kind: "provider",
    name: "OpenRouter",
    description: "用于接入多模型供应商，并为不同智能体分配不同模型。",
    version: "0.1.0",
    source: "builtin",
    enabled: false,
    installed: true,
    permissions: network,
    tags: ["模型", "路由"],
  },
  {
    id: "railwise.provider.openai_compatible",
    kind: "provider",
    name: "OpenAI 兼容 Provider",
    description: "接入自托管或第三方 OpenAI 兼容 API。",
    version: "0.1.0",
    source: "builtin",
    enabled: false,
    installed: true,
    permissions: network,
    tags: ["模型", "兼容"],
  },
  {
    id: "railwise.mcp.filesystem",
    kind: "mcp",
    name: "文件系统 MCP",
    description: "面向当前工作区的文件检索与读写连接能力。",
    version: "0.1.0",
    source: "builtin",
    enabled: false,
    installed: true,
    permissions: external,
    tags: ["MCP", "文件"],
  },
  {
    id: "railwise.mcp.feishu",
    kind: "mcp",
    name: "飞书知识库 MCP",
    description: "连接企业云文档、知识库和项目协作资料。",
    version: "0.1.0",
    source: "builtin",
    enabled: false,
    installed: false,
    permissions: network,
    tags: ["MCP", "飞书", "知识库"],
  },
]

export function effectiveCapabilities(list: CapabilityManifest[]) {
  if (list.length) return list
  return starterCapabilities
}

export function toggleStarterCapability(list: CapabilityManifest[], id: string, enabled: boolean) {
  const target = list.find((item) => item.id === id)
  return list.map((item) => {
    if (item.id === id) return { ...item, enabled }
    if (enabled && target?.kind === "harness_profile" && item.kind === "harness_profile") return { ...item, enabled: false }
    return item
  })
}

export function updateStarterCapability(list: CapabilityManifest[], id: string, patch: Partial<CapabilityManifest>) {
  return list.map((item) => (item.id === id ? { ...item, ...patch } : item))
}
