import { Config } from "effect"

function truthy(key: string) {
  const value = process.env[key]?.toLowerCase()
  return value === "true" || value === "1"
}

function falsy(key: string) {
  const value = process.env[key]?.toLowerCase()
  return value === "false" || value === "0"
}

function number(key: string) {
  const value = process.env[key]
  if (!value) return undefined
  const parsed = Number(value)
  return Number.isInteger(parsed) && parsed > 0 ? parsed : undefined
}

const RAILWISE_EXPERIMENTAL = truthy("RAILWISE_EXPERIMENTAL")
const RAILWISE_DISABLE_CLAUDE_CODE = truthy("RAILWISE_DISABLE_CLAUDE_CODE")
const RAILWISE_DISABLE_CLAUDE_CODE_SKILLS =
  RAILWISE_DISABLE_CLAUDE_CODE || truthy("RAILWISE_DISABLE_CLAUDE_CODE_SKILLS")
const copy = process.env["RAILWISE_EXPERIMENTAL_DISABLE_COPY_ON_SELECT"]

export const Flag = {
  OTEL_EXPORTER_OTLP_ENDPOINT: process.env["OTEL_EXPORTER_OTLP_ENDPOINT"],
  OTEL_EXPORTER_OTLP_HEADERS: process.env["OTEL_EXPORTER_OTLP_HEADERS"],

  RAILWISE_AUTO_SHARE: truthy("RAILWISE_AUTO_SHARE"),
  RAILWISE_AUTO_HEAP_SNAPSHOT: truthy("RAILWISE_AUTO_HEAP_SNAPSHOT"),
  RAILWISE_GIT_BASH_PATH: process.env["RAILWISE_GIT_BASH_PATH"],
  RAILWISE_CONFIG: process.env["RAILWISE_CONFIG"],
  RAILWISE_CONFIG_CONTENT: process.env["RAILWISE_CONFIG_CONTENT"],
  RAILWISE_DISABLE_AUTOUPDATE: truthy("RAILWISE_DISABLE_AUTOUPDATE"),
  RAILWISE_ALWAYS_NOTIFY_UPDATE: truthy("RAILWISE_ALWAYS_NOTIFY_UPDATE"),
  RAILWISE_DISABLE_PRUNE: truthy("RAILWISE_DISABLE_PRUNE"),
  RAILWISE_DISABLE_TERMINAL_TITLE: truthy("RAILWISE_DISABLE_TERMINAL_TITLE"),
  RAILWISE_SHOW_TTFD: truthy("RAILWISE_SHOW_TTFD"),
  RAILWISE_PERMISSION: process.env["RAILWISE_PERMISSION"],
  RAILWISE_DISABLE_DEFAULT_PLUGINS: truthy("RAILWISE_DISABLE_DEFAULT_PLUGINS"),
  RAILWISE_DISABLE_LSP_DOWNLOAD: truthy("RAILWISE_DISABLE_LSP_DOWNLOAD"),
  RAILWISE_ENABLE_EXPERIMENTAL_MODELS: truthy("RAILWISE_ENABLE_EXPERIMENTAL_MODELS"),
  RAILWISE_DISABLE_AUTOCOMPACT: truthy("RAILWISE_DISABLE_AUTOCOMPACT"),
  RAILWISE_DISABLE_MODELS_FETCH: truthy("RAILWISE_DISABLE_MODELS_FETCH"),
  RAILWISE_DISABLE_MOUSE: truthy("RAILWISE_DISABLE_MOUSE"),
  RAILWISE_DISABLE_CLAUDE_CODE,
  RAILWISE_DISABLE_CLAUDE_CODE_PROMPT: RAILWISE_DISABLE_CLAUDE_CODE || truthy("RAILWISE_DISABLE_CLAUDE_CODE_PROMPT"),
  RAILWISE_DISABLE_CLAUDE_CODE_SKILLS,
  RAILWISE_DISABLE_EXTERNAL_SKILLS: RAILWISE_DISABLE_CLAUDE_CODE_SKILLS || truthy("RAILWISE_DISABLE_EXTERNAL_SKILLS"),
  RAILWISE_FAKE_VCS: process.env["RAILWISE_FAKE_VCS"],
  RAILWISE_SERVER_PASSWORD: process.env["RAILWISE_SERVER_PASSWORD"],
  RAILWISE_SERVER_USERNAME: process.env["RAILWISE_SERVER_USERNAME"],
  RAILWISE_ENABLE_QUESTION_TOOL: truthy("RAILWISE_ENABLE_QUESTION_TOOL"),

  // Experimental
  RAILWISE_EXPERIMENTAL,
  RAILWISE_EXPERIMENTAL_FILEWATCHER: Config.boolean("RAILWISE_EXPERIMENTAL_FILEWATCHER").pipe(
    Config.withDefault(false),
  ),
  RAILWISE_EXPERIMENTAL_DISABLE_FILEWATCHER: Config.boolean("RAILWISE_EXPERIMENTAL_DISABLE_FILEWATCHER").pipe(
    Config.withDefault(false),
  ),
  RAILWISE_EXPERIMENTAL_ICON_DISCOVERY: RAILWISE_EXPERIMENTAL || truthy("RAILWISE_EXPERIMENTAL_ICON_DISCOVERY"),
  RAILWISE_EXPERIMENTAL_DISABLE_COPY_ON_SELECT:
    copy === undefined ? process.platform === "win32" : truthy("RAILWISE_EXPERIMENTAL_DISABLE_COPY_ON_SELECT"),
  RAILWISE_ENABLE_EXA: truthy("RAILWISE_ENABLE_EXA") || RAILWISE_EXPERIMENTAL || truthy("RAILWISE_EXPERIMENTAL_EXA"),
  RAILWISE_EXPERIMENTAL_BASH_DEFAULT_TIMEOUT_MS: number("RAILWISE_EXPERIMENTAL_BASH_DEFAULT_TIMEOUT_MS"),
  RAILWISE_EXPERIMENTAL_OUTPUT_TOKEN_MAX: number("RAILWISE_EXPERIMENTAL_OUTPUT_TOKEN_MAX"),
  RAILWISE_EXPERIMENTAL_OXFMT: RAILWISE_EXPERIMENTAL || truthy("RAILWISE_EXPERIMENTAL_OXFMT"),
  RAILWISE_EXPERIMENTAL_LSP_TY: truthy("RAILWISE_EXPERIMENTAL_LSP_TY"),
  RAILWISE_EXPERIMENTAL_LSP_TOOL: RAILWISE_EXPERIMENTAL || truthy("RAILWISE_EXPERIMENTAL_LSP_TOOL"),
  RAILWISE_EXPERIMENTAL_PLAN_MODE: RAILWISE_EXPERIMENTAL || truthy("RAILWISE_EXPERIMENTAL_PLAN_MODE"),
  RAILWISE_EXPERIMENTAL_MARKDOWN: !falsy("RAILWISE_EXPERIMENTAL_MARKDOWN"),
  RAILWISE_MODELS_URL: process.env["RAILWISE_MODELS_URL"],
  RAILWISE_MODELS_PATH: process.env["RAILWISE_MODELS_PATH"],
  RAILWISE_DISABLE_EMBEDDED_WEB_UI: truthy("RAILWISE_DISABLE_EMBEDDED_WEB_UI"),
  RAILWISE_DB: process.env["RAILWISE_DB"],
  RAILWISE_DISABLE_CHANNEL_DB: truthy("RAILWISE_DISABLE_CHANNEL_DB"),
  RAILWISE_SKIP_MIGRATIONS: truthy("RAILWISE_SKIP_MIGRATIONS"),
  RAILWISE_STRICT_CONFIG_DEPS: truthy("RAILWISE_STRICT_CONFIG_DEPS"),

  RAILWISE_WORKSPACE_ID: process.env["RAILWISE_WORKSPACE_ID"],
  RAILWISE_EXPERIMENTAL_HTTPAPI: truthy("RAILWISE_EXPERIMENTAL_HTTPAPI"),
  RAILWISE_EXPERIMENTAL_WORKSPACES: RAILWISE_EXPERIMENTAL || truthy("RAILWISE_EXPERIMENTAL_WORKSPACES"),

  // Evaluated at access time (not module load) because tests, the CLI, and
  // external tooling set these env vars at runtime.
  get RAILWISE_DISABLE_PROJECT_CONFIG() {
    return truthy("RAILWISE_DISABLE_PROJECT_CONFIG")
  },
  get RAILWISE_TUI_CONFIG() {
    return process.env["RAILWISE_TUI_CONFIG"]
  },
  get RAILWISE_CONFIG_DIR() {
    return process.env["RAILWISE_CONFIG_DIR"]
  },
  get RAILWISE_PURE() {
    return truthy("RAILWISE_PURE")
  },
  get RAILWISE_PLUGIN_META_FILE() {
    return process.env["RAILWISE_PLUGIN_META_FILE"]
  },
  get RAILWISE_CLIENT() {
    return process.env["RAILWISE_CLIENT"] ?? "cli"
  },
}
