import path from "path"

type Request = (url: string) => Promise<Response>

export const snapshot = (dir: string) => path.join(dir, "src/provider/models-snapshot.ts")
const fixture = (dir: string) => path.join(dir, "test/tool/fixtures/models-api.json")
export const source = (data: string) =>
  `// Auto-generated by build.ts - do not edit\nexport const snapshot = ${data.trim()} as const\n`

export async function models(dir: string, request: Request = fetch) {
  if (process.env.MODELS_DEV_API_JSON) return Bun.file(process.env.MODELS_DEV_API_JSON).text()

  const url = process.env.RAILWISE_MODELS_URL || "https://models.dev"
  const fallback = async (reason: string) => {
    if (await Bun.file(snapshot(dir)).exists()) {
      console.warn(`Unable to refresh models.dev snapshot (${reason}); reusing ${path.relative(dir, snapshot(dir))}`)
      return { handled: true, data: undefined }
    }
    if (await Bun.file(fixture(dir)).exists()) {
      console.warn(`Unable to refresh models.dev snapshot (${reason}); seeding from ${path.relative(dir, fixture(dir))}`)
      return { handled: true, data: await Bun.file(fixture(dir)).text() }
    }
    return { handled: false, data: undefined }
  }

  const response = await request(`${url}/api.json`).catch((error: unknown) => error)
  if (response instanceof Response) {
    if (response.ok) return response.text()
    const seeded = await fallback(`${response.status} ${response.statusText}`)
    if (seeded.handled) return seeded.data
    throw new Error(`Failed to fetch ${url}/api.json: ${response.status} ${response.statusText}`)
  }

  const seeded = await fallback(response instanceof Error ? response.message : "network unavailable")
  if (seeded.handled) return seeded.data
  throw response
}
