import { expect, test } from "./helpers/app"
import { visible } from "./helpers/wait"

const worktree = "/Users/WANGJIAWEI/CODE/RAILWISE-CLI"
const project = () => [{ id: "railwise-cli", worktree, time: { created: Date.now(), updated: Date.now() } }]

test("能力市场保持极简能力包入口", async ({ launchApp }) => {
  const { page } = await launchApp("/marketplace", { projects: project() })

  await visible(page.locator("[data-testid=marketplace-page]"))
  await expect(page.locator("[data-component=sidebar-nav-desktop]")).toBeVisible()
  await expect(page.locator("[data-testid=sidebar-project-meta]").first()).toHaveText("项目工作区")
  await expect(page.locator("[data-component=sidebar-nav-desktop]")).not.toContainText(worktree)
  await expect(page.locator("[data-testid=agent-marketplace]")).toBeVisible()
  await expect(page.getByRole("button", { name: "技能" })).toBeVisible()
  await expect(page.locator("[data-testid=marketplace-row-state-agents]")).toContainText("已启用")
  await expect(page.locator("[data-testid=marketplace-row-state-tools]")).toContainText("已启用")
  await expect(page.locator("[data-testid=marketplace-row-state-skills]")).toContainText("已启用")
  await expect(page.locator("[data-testid=marketplace-row-state-providers]")).toContainText("待接入")
  await expect(page.locator("[data-testid=marketplace-preview-agents]")).toContainText("RAILWISE")
  await expect(page.locator("[data-testid=marketplace-permissions-agents]")).toContainText("RAILWISE 默认协作")
  await expect(page.locator("[data-testid=marketplace-permissions-agents]")).toContainText("文件读取")
  const grid = page.locator("[data-testid=marketplace-capability-grid]")
  await expect(grid).toContainText("RAILWISE 默认协作")
  await expect(grid).toContainText("已启用")
  await expect(grid).toContainText("内置")
  await expect(grid).toContainText("低风险")
  await page.locator("[data-testid=marketplace-search]").fill("不存在的能力")
  await expect(page.locator("[data-testid=marketplace-capability-empty]")).toContainText("没有匹配的能力")
  await page.locator("[data-testid=marketplace-search]").fill("")
  await page.locator("[data-testid=marketplace-row-tools]").click()
  await expect(page.locator("[data-testid=marketplace-state-tools]")).toContainText("已启用")
  await expect(page.locator("[data-testid=marketplace-preview-tools]")).toContainText("规范条文查询")
  await expect(page.locator("[data-testid=marketplace-permissions-tools]")).toContainText("本地文件读取")
  await expect(grid).toContainText("本地文件读取")
  await expect(grid).toContainText("水准闭合差检核")
  await expect(grid).toContainText("复测资料检查")
  await expect(grid).toContainText("DXF 图层检查")
  await expect(grid).toContainText("PPT 汇报生成")
  await expect(grid).toContainText("文件")
  await page.locator("[data-testid=marketplace-search]").fill("水准")
  const leveling = page.locator('[data-capability-id="railwise.tool.survey_calculator_leveling_closure"]')
  await expect(leveling).toContainText("已启用")
  await expect(leveling.getByTestId("marketplace-capability-bindings")).toContainText("外业数据首检员")
  await expect(leveling.getByTestId("marketplace-capability-bindings")).toContainText("数据首检与趋势分析")
  await page.locator("[data-testid=marketplace-search]").fill("")
  await page.locator("[data-testid=marketplace-row-skills]").click()
  await expect(page.locator("[data-testid=marketplace-preview-skills]")).toContainText("monitoring-design")
  await expect(page.locator("[data-testid=marketplace-permissions-skills]")).toContainText("轨道交通监测方案")
  await expect(grid).toContainText("轨道交通监测方案")
  await expect(grid).toContainText("运营期监测")
  await expect(grid).toContainText("规范条文速查")
  await expect(grid).toContainText("成果报告写作")
  await page.locator("[data-testid=marketplace-search]").fill("规范条文")
  const standard = page.locator('[data-capability-id="railwise.skill.standard-reference"]')
  await expect(standard).toContainText("已启用")
  await expect(standard.getByTestId("marketplace-capability-bindings")).toContainText("规范资料管理员")
  await expect(standard.getByTestId("marketplace-capability-bindings")).toContainText("质量审查专家")
  await expect(standard.getByTestId("marketplace-capability-bindings")).toContainText("规范引用复核")
  await expect(standard.getByTestId("marketplace-capability-action")).toContainText("停用")
  await standard.getByTestId("marketplace-capability-action").click()
  await expect(standard).toContainText("待启用")
  await expect(standard).toContainText("当前已停用")
  await expect(standard.getByTestId("marketplace-capability-action")).toContainText("启用")
  await standard.getByTestId("marketplace-capability-action").click()
  await expect(standard).toContainText("已启用")
  await page.locator("[data-testid=marketplace-search]").fill("")
  await page.locator("[data-testid=marketplace-row-providers]").click()
  await expect(page.locator("[data-testid=marketplace-state-providers]")).toContainText("待接入")
  await expect(page.locator("[data-testid=marketplace-permissions-providers]")).toContainText("DeepSeek")
  await expect(page.locator("[data-testid=marketplace-permissions-providers]")).toContainText("网络 / 密钥")
  await expect(grid).toContainText("DeepSeek")
  await expect(grid).toContainText("网络 / 密钥")
  await expect(grid.getByRole("button", { name: "接入模型" })).toBeVisible()
  await expect(page.getByText("进入高级管理")).toHaveCount(0)
  await expect(page.locator("[data-testid=agent-collaboration-start]")).toHaveCount(0)
  await expect(page.locator("[data-testid=agent-model-routing]")).toHaveCount(0)
})

test("智能体工作台通过统一外壳打开", async ({ launchApp }) => {
  const { page } = await launchApp("/agents", { projects: project() })

  await visible(page.locator("[data-testid=agents-page]"))
  expect(new URL(page.url()).pathname).toBe("/agents")
  await expect(page.locator("[data-component=sidebar-nav-desktop]")).toBeVisible()
  await expect(page.locator("[data-testid=sidebar-project-meta]").first()).toHaveText("项目工作区")
  await expect(page.locator("[data-component=sidebar-nav-desktop]")).not.toContainText(worktree)
  await expect(page.locator("[data-testid=agent-collaboration-start]")).toBeVisible()
  await expect(page.locator("[data-testid=agent-model-routing]")).toBeVisible()
  await expect(page.getByRole("heading", { name: "RAILWISE 协作" })).toBeVisible()
  await expect(page.getByText("能力市场").first()).toBeVisible()
  await expect(page.locator("#agent-library").getByRole("heading", { name: "智能体" })).toBeVisible()
  await expect(page.locator("[data-testid=agent-project-directory]")).toHaveCount(0)
  await expect(page.getByText("高级智能体管理")).toHaveCount(0)
  await expect(page.getByText("智能体矩阵")).toHaveCount(0)
})

test("能力市场进入 chief_manager 配置并验证保存入口", async ({ launchApp }) => {
  const { page } = await launchApp("/marketplace", { projects: project() })

  await visible(page.locator("[data-testid=marketplace-page]"))
  await page.locator("[data-testid=marketplace-open-agents]").click()
  await visible(page.locator("[data-testid=agents-page]"))
  await page.locator("[data-testid=agent-card-chief_manager]").click()

  await visible(page.locator("[data-testid=agent-detail-page]"))
  await expect(page.locator("[data-testid=agent-detail-shell]")).toContainText("智能体配置")
  await expect(page.getByRole("heading", { name: "能力定义" })).toBeVisible()
  await expect(page.locator("[data-testid=agent-capability-routing]")).toContainText("可调用能力")
  await expect(page.locator("[data-testid=agent-capability-routing]")).toContainText("规范条文速查")
  await expect(page.locator("[data-testid=agent-capability-routing]")).toContainText("规范引用复核")
  await visible(page.locator("[data-testid=agent-prompt-editor]"))
  await expect(page.locator("[data-testid=save-agent-btn]")).toContainText(/已保存|保存/)
  await expect(page.getByText("Markdown 配置")).toHaveCount(0)
  await expect(page.getByText("高级")).toHaveCount(0)
})

test("能力市场可以进入执行中心", async ({ launchApp }) => {
  const { page } = await launchApp("/marketplace", { projects: project() })

  await visible(page.locator("[data-testid=marketplace-page]"))
  await page.getByRole("button", { name: "执行层" }).click()
  await page.locator("[data-testid=marketplace-open-harness]").click()

  await visible(page.locator("[data-testid=harness-page]"))
  await expect(page).toHaveURL(/\/harness$/)
  await expect(page.locator("[data-component=sidebar-nav-desktop]")).toBeVisible()
  await expect(page.locator("[data-testid=sidebar-project-meta]").first()).toHaveText("项目工作区")
  await expect(page.locator("[data-component=sidebar-nav-desktop]")).not.toContainText(worktree)
  await expect(page.getByRole("heading", { name: "执行中心" })).toBeVisible()
  await expect(page.locator("[data-testid=harness-shell]")).toBeVisible()
})

test("执行层可以通过统一外壳打开", async ({ launchApp }) => {
  const { page } = await launchApp("/harness", { projects: project() })

  await visible(page.locator("[data-testid=harness-page]"))
  await expect(page.locator("[data-component=sidebar-nav-desktop]")).toBeVisible()
  await expect(page.locator("[data-testid=sidebar-project-meta]").first()).toHaveText("项目工作区")
  await expect(page.locator("[data-component=sidebar-nav-desktop]")).not.toContainText(worktree)
  await expect(page.getByRole("heading", { name: "执行中心" })).toBeVisible()
  await expect(page.locator("[data-testid=harness-shell]")).toBeVisible()
  await expect(page.locator("[data-testid=harness-permission-item]")).toBeVisible()
  await expect(page.locator("[data-testid=harness-permissions]")).toContainText("成果报告.md")
  const permissionLink = page.locator("[data-testid=harness-permission-open-session]").first()
  await expect(permissionLink).toContainText("定位处理")
  await expect(permissionLink).toHaveAttribute("href", /#session-prompt-dock$/)
  await expect(page.locator("[data-testid=harness-timeline]")).toContainText("执行时间线")
  await expect(page.locator("[data-testid=harness-timeline]")).toContainText(/还没有会话执行记录|运营期监测预警复核/)
  await expect(page.locator("[data-testid=harness-timeline-open-session]").first()).toHaveAttribute("href", /#session-prompt-dock$/)
  await expect(page.locator("[data-testid=harness-session-detail]")).toContainText(/还没有可查看的会话|运营期监测预警复核/)
  await expect(page.locator("[data-testid=harness-detail-open-session]").first()).toHaveAttribute("href", /#session-prompt-dock$/)
  await expect(page.getByText("执行层状态")).toHaveCount(0)
  await permissionLink.click()
  await expect(page).toHaveURL(/\/session\/queue-e2e#session-prompt-dock$/)
  await expect(page.locator("#session-prompt-dock")).toBeVisible()
})
