import type { CapabilityManifest, CapabilityPermission } from "./schema"

const read: CapabilityPermission = {
  filesystem: "read",
  network: false,
  shell: false,
  external_directory: false,
  secrets: false,
}

const write: CapabilityPermission = {
  filesystem: "write",
  network: false,
  shell: false,
  external_directory: false,
  secrets: false,
}

type Item = {
  id: string
  name: string
  description: string
  tags: string[]
  permissions?: CapabilityPermission
}

const agents: Item[] = [
  {
    id: "chief_manager",
    name: "RAILWISE 默认协作",
    description: "理解用户任务、拆解计划，并协调专业智能体、工具和 Skill 完成交付。",
    tags: ["协作", "任务拆解", "默认"],
  },
  {
    id: "source_ingestor",
    name: "资料入库专员",
    description: "清点规范、招标文件、监测台账、历史成果和原始数据，整理成可处理资料包。",
    tags: ["资料", "清点", "入库"],
  },
  {
    id: "qa_inspector",
    name: "外业数据首检",
    description: "检查外业原始数据完整性、规范性、闭合差和明显粗差，拦截无效数据。",
    tags: ["外业", "质检", "闭合差"],
  },
  {
    id: "adjustment_computer",
    name: "严密平差计算",
    description: "负责水准网、导线网、平面控制网和 CPIII 控制网的工具化计算与精度评定。",
    tags: ["平差", "计算", "精度"],
  },
  {
    id: "data_analyst",
    name: "测绘数据分析",
    description: "处理测绘、监测和复测数据，进行趋势分析、异常识别和预警研判。",
    tags: ["数据", "趋势", "预警"],
  },
  {
    id: "norm_librarian",
    name: "规范资料管理员",
    description: "查询工程测绘与监测规范条文，固化引用依据并维护规范知识。",
    tags: ["规范", "条文", "依据"],
  },
  {
    id: "solution_architect",
    name: "技术方案架构师",
    description: "设计监测方案、测点布设、仪器选型和测绘技术路线。",
    tags: ["方案", "设计", "仪器"],
  },
  {
    id: "cpiii_specialist",
    name: "CPIII 测量专家",
    description: "负责高铁和城轨 CPIII 复测方案、自由设站观测设计与成果审查。",
    tags: ["CPIII", "复测", "控制网"],
  },
  {
    id: "technical_writer",
    name: "工程报告编制",
    description: "把方案、数据和审查意见整理成监测日报、周报、月报和总结报告。",
    tags: ["报告", "写作", "交付"],
  },
  {
    id: "qa_reviewer",
    name: "技术质量审查",
    description: "对技术方案、报告和投标文件做规范合规终审，指出红线问题和修改要求。",
    tags: ["审查", "合规", "质量"],
  },
  {
    id: "commercial_specialist",
    name: "商务招投标",
    description: "处理商务报价、标书资质响应、合同风险审核和结算收款材料。",
    tags: ["投标", "合同", "商务"],
  },
  {
    id: "knowledge_curator",
    name: "知识库整理员",
    description: "把项目案例、技术问答、复盘经验沉淀为可复用企业知识。",
    tags: ["知识库", "案例", "复盘"],
  },
]

const skills: Item[] = [
  {
    id: "rail-monitoring-plan",
    name: "轨道交通监测方案",
    description: "编制轨道交通控制保护区、地保监测和专家评审方案。",
    tags: ["轨道交通", "监测", "方案"],
  },
  {
    id: "monitoring-design",
    name: "工程监测方案设计",
    description: "围绕铁路、市政和基坑监测任务，生成监测方案、点位布设和频率建议。",
    tags: ["测绘", "监测", "方案"],
  },
  {
    id: "operational-monitoring",
    name: "运营期监测",
    description: "处理运营期沉降、水平位移、收敛和预警处置等监测资料。",
    tags: ["运营期", "监测", "预警"],
    permissions: write,
  },
  {
    id: "data-analysis",
    name: "测绘数据分析",
    description: "对外业测量、监测和复测数据进行首检、趋势分析和异常识别。",
    tags: ["数据分析", "平差", "复核"],
  },
  {
    id: "standard-reference",
    name: "规范条文速查",
    description: "检索常用工程测绘、监测和交付规范，提取条文依据与引用建议。",
    tags: ["规范", "条文", "依据"],
  },
  {
    id: "report-writing",
    name: "成果报告写作",
    description: "生成测绘、监测、复测和阶段汇报类成果报告初稿，并进行技术审校。",
    tags: ["报告", "审校", "交付"],
    permissions: write,
  },
  {
    id: "excel-operations",
    name: "表格数据处理",
    description: "整理 Excel 数据表、计算检查项、生成统计结果和可交付表格。",
    tags: ["Excel", "表格", "统计"],
    permissions: write,
  },
  {
    id: "docx-generation",
    name: "Word 成果生成",
    description: "生成 Word 成果文档、套用模板并整理报告结构。",
    tags: ["Word", "报告", "模板"],
    permissions: write,
  },
  {
    id: "docx",
    name: "DOCX 文件处理",
    description: "读取、编辑和生成 Word 文档，支持目录、页眉页脚、表格和模板。",
    tags: ["DOCX", "Word", "文件"],
    permissions: write,
  },
  {
    id: "pptx",
    name: "PPT 汇报生成",
    description: "根据项目阶段、数据结论和交付对象生成汇报幻灯片。",
    tags: ["PPT", "汇报", "演示"],
    permissions: write,
  },
  {
    id: "pdf",
    name: "PDF 表单与检查",
    description: "检查 PDF 表单、提取结构信息并辅助生成带注释的 PDF 交付材料。",
    tags: ["PDF", "表单", "检查"],
    permissions: write,
  },
  {
    id: "xlsx",
    name: "XLSX 文件处理",
    description: "读取、校验和生成 XLSX 工作簿，用于工程数据统计与交付。",
    tags: ["XLSX", "表格", "交付"],
    permissions: write,
  },
  {
    id: "bidding-knowledge",
    name: "投标资料知识库",
    description: "整理招投标资料、资质响应、技术方案和商务材料检查清单。",
    tags: ["投标", "资料", "知识库"],
  },
  {
    id: "frontend-design",
    name: "工程前端设计",
    description: "为监测平台、数据看板和内部管理系统生成工程行业 UI 方案。",
    tags: ["前端", "设计", "看板"],
  },
  {
    id: "canvas-design",
    name: "可视化设计",
    description: "制作项目展示、成果图示、汇报版式和可视化素材。",
    tags: ["设计", "可视化", "汇报"],
    permissions: write,
  },
  {
    id: "humanizer",
    name: "文稿润色",
    description: "优化技术报告、投标文本和汇报材料的表达，使其更自然、专业。",
    tags: ["润色", "文稿", "审校"],
  },
  {
    id: "doc-coauthoring",
    name: "文档协同审阅",
    description: "围绕多人协作场景进行文档审阅、修改建议和版本意见整理。",
    tags: ["协同", "审阅", "文档"],
    permissions: write,
  },
  {
    id: "internal-comms",
    name: "内部沟通写作",
    description: "编写项目进展、领导汇报、FAQ、事故说明和团队沟通材料。",
    tags: ["沟通", "汇报", "文档"],
  },
  {
    id: "brand-guidelines",
    name: "品牌规范参考",
    description: "在文档、演示和页面中套用统一的品牌色、字体和视觉规范。",
    tags: ["品牌", "视觉", "规范"],
  },
  {
    id: "theme-factory",
    name: "主题样式工厂",
    description: "为报告、网页、幻灯片和设计稿生成一致的配色与字体主题。",
    tags: ["主题", "样式", "设计"],
  },
  {
    id: "web-artifacts-builder",
    name: "Web Artifact 构建",
    description: "构建复杂 HTML/React 交互原型、报告页面和可视化组件。",
    tags: ["Web", "Artifact", "React"],
    permissions: write,
  },
  {
    id: "webapp-testing",
    name: "Web 应用测试",
    description: "使用 Playwright 调试本地 Web 应用、验证 UI 行为并采集截图。",
    tags: ["测试", "Playwright", "前端"],
  },
  {
    id: "bun-file-io",
    name: "Bun 文件读写",
    description: "提供 Bun 文件读写、扫描和目录处理的工程实现规范。",
    tags: ["Bun", "文件", "开发"],
  },
  {
    id: "mcp-builder",
    name: "MCP 服务构建",
    description: "设计和实现高质量 MCP Server，连接外部服务和企业能力。",
    tags: ["MCP", "工具", "集成"],
    permissions: write,
  },
  {
    id: "skill-creator",
    name: "Skill 创建器",
    description: "创建、改进和评测新的 Skill，并优化触发描述与执行流程。",
    tags: ["Skill", "创建", "评测"],
    permissions: write,
  },
  {
    id: "claude-api",
    name: "Claude API 开发",
    description: "构建、调试和优化 Claude API / Anthropic SDK 应用。",
    tags: ["Claude", "API", "开发"],
  },
  {
    id: "algorithmic-art",
    name: "算法艺术生成",
    description: "使用 p5.js、随机种子和交互参数生成原创算法艺术。",
    tags: ["艺术", "p5.js", "生成"],
    permissions: write,
  },
  {
    id: "slack-gif-creator",
    name: "Slack GIF 生成",
    description: "生成适合 Slack 使用的动画 GIF，并控制尺寸、帧率和文件大小。",
    tags: ["GIF", "Slack", "动画"],
    permissions: write,
  },
]

const tools: Item[] = [
  {
    id: "task",
    name: "智能体任务调度",
    description: "把用户任务分派给 RAILWISE 和专业智能体，并汇总执行结果。",
    tags: ["智能体", "调度", "协作"],
  },
  {
    id: "skill",
    name: "Skill 加载器",
    description: "按任务加载专业 Skill，让智能体获得对应作业流程和检查清单。",
    tags: ["Skill", "加载", "流程"],
  },
  {
    id: "file_reader",
    name: "本地文件读取",
    description: "读取当前工作区内的工程文件。",
    tags: ["文件", "本地", "工作区"],
  },
  {
    id: "standard_query_query_standard",
    name: "规范条文查询",
    description: "检索工程测绘、轨道交通监测和成果交付相关规范条文。",
    tags: ["规范", "条文", "检索"],
  },
  {
    id: "survey_calculator_leveling_closure",
    name: "水准闭合差检核",
    description: "对水准路线闭合差、限差和观测成果进行快速复核。",
    tags: ["水准", "闭合差", "复核"],
  },
  {
    id: "resurvey_material_check",
    name: "复测资料检查",
    description: "检查复测资料目录、控制点成果、观测记录和缺失文件。",
    tags: ["复测", "资料", "缺失"],
  },
  {
    id: "monitoring_data_first_check",
    name: "监测数据首检",
    description: "对沉降、位移、收敛等监测数据进行异常点和预警状态初筛。",
    tags: ["监测", "异常", "预警"],
  },
  {
    id: "dxf_layer_inspector",
    name: "DXF 图层检查",
    description: "检查 CAD/DXF 图层命名、关键构筑物线型和成果图交付完整性。",
    tags: ["DXF", "CAD", "图层"],
  },
  {
    id: "xlsx_quality_checker",
    name: "Excel 表格校验",
    description: "检查 XLSX/CSV 表格字段、空值、单位、阈值和统计结果。",
    tags: ["Excel", "CSV", "校验"],
  },
  {
    id: "docx_report_formatter",
    name: "Word 成果排版",
    description: "检查并整理 Word 成果报告结构、目录、表格和交付格式。",
    tags: ["Word", "报告", "排版"],
    permissions: write,
  },
  {
    id: "pptx_brief_builder",
    name: "PPT 汇报生成",
    description: "基于项目阶段、数据结论和风险提示生成汇报幻灯片。",
    tags: ["PPT", "汇报", "生成"],
    permissions: write,
  },
  {
    id: "pdf_form_checker",
    name: "PDF 表单检查",
    description: "提取并检查 PDF 表单、签章页和资料归档信息。",
    tags: ["PDF", "表单", "归档"],
  },
]

function manifest(kind: CapabilityManifest["kind"], item: Item): CapabilityManifest {
  return {
    id: `railwise.${kind === "harness_profile" ? "harness" : kind}.${item.id}`,
    kind,
    name: item.name,
    description: item.description,
    version: "0.1.0",
    source: "builtin",
    enabled: true,
    installed: true,
    permissions: item.permissions ?? read,
    tags: item.tags,
  }
}

export const builtins: CapabilityManifest[] = [
  {
    id: "railwise.harness.safe",
    kind: "harness_profile",
    name: "本地安全模式",
    description: "默认要求用户确认写文件、执行命令和访问外部目录。",
    version: "0.1.0",
    source: "builtin",
    enabled: true,
    installed: true,
    permissions: read,
    tags: ["安全", "默认"],
  },
  ...agents.map((item) => manifest("agent", item)),
  ...tools.map((item) => manifest("tool", item)),
  ...skills.map((item) => manifest("skill", item)),
  {
    id: "railwise.workflow.metro_monitoring_report",
    kind: "workflow",
    name: "地铁监测月报",
    description: "串联数据首检、异常分析、报告编制和技术审校。",
    version: "0.1.0",
    source: "builtin",
    enabled: true,
    installed: true,
    permissions: write,
    tags: ["监测", "报告"],
  },
  {
    id: "railwise.workflow.cpiii_resurvey",
    kind: "workflow",
    name: "CPIII 复测预案",
    description: "串联资料清点、规范查询、控制网计算和成果审查。",
    version: "0.1.0",
    source: "builtin",
    enabled: true,
    installed: true,
    permissions: read,
    tags: ["CPIII", "复测", "工作流"],
  },
  {
    id: "railwise.mcp.knowledge_base",
    kind: "mcp",
    name: "知识库连接器",
    description: "连接本地或企业知识库，供规范检索和资料审查使用。",
    version: "0.1.0",
    source: "builtin",
    enabled: false,
    installed: true,
    permissions: {
      filesystem: "read",
      network: true,
      shell: false,
      external_directory: true,
      secrets: true,
    },
    tags: ["知识库", "MCP"],
  },
  {
    id: "railwise.mcp.local_tools",
    kind: "mcp",
    name: "本地工具桥接",
    description: "连接当前工作区允许的本地工具能力。",
    version: "0.1.0",
    source: "builtin",
    enabled: false,
    installed: true,
    permissions: {
      filesystem: "read",
      network: false,
      shell: true,
      external_directory: false,
      secrets: false,
    },
    tags: ["MCP", "本地"],
  },
  {
    id: "railwise.provider.deepseek",
    kind: "provider",
    name: "DeepSeek",
    description: "推荐默认模型 Provider，可为不同智能体配置不同模型。",
    version: "0.1.0",
    source: "builtin",
    enabled: false,
    installed: true,
    permissions: {
      filesystem: "none",
      network: true,
      shell: false,
      external_directory: false,
      secrets: true,
    },
    tags: ["模型", "推荐"],
  },
  {
    id: "railwise.provider.openrouter",
    kind: "provider",
    name: "OpenRouter",
    description: "聚合式模型 Provider，可让不同智能体选择不同厂商和模型。",
    version: "0.1.0",
    source: "builtin",
    enabled: false,
    installed: true,
    permissions: {
      filesystem: "none",
      network: true,
      shell: false,
      external_directory: false,
      secrets: true,
    },
    tags: ["模型", "多模型"],
  },
  {
    id: "railwise.provider.openai_compatible",
    kind: "provider",
    name: "OpenAI 兼容",
    description: "接入兼容 OpenAI API 的本地或云端模型服务，适合企业自定义模型网关。",
    version: "0.1.0",
    source: "builtin",
    enabled: false,
    installed: true,
    permissions: {
      filesystem: "none",
      network: true,
      shell: false,
      external_directory: false,
      secrets: true,
    },
    tags: ["模型", "兼容接口"],
  },
]
