import type { CapabilityManifest } from "./schema"

export const builtins: CapabilityManifest[] = [
  {
    id: "railwise.harness.safe",
    kind: "harness_profile",
    name: "本地安全模式",
    description: "默认要求用户确认写文件、执行命令和访问外部目录。",
    version: "0.1.0",
    source: "builtin",
    enabled: true,
    installed: true,
    permissions: {
      filesystem: "read",
      network: false,
      shell: false,
      external_directory: false,
      secrets: false,
    },
    tags: ["安全", "默认"],
  },
  {
    id: "railwise.agent.chief_manager",
    kind: "agent",
    name: "项目总控",
    description: "理解任务、拆解计划，并调度专业智能体执行。",
    version: "0.1.0",
    source: "builtin",
    enabled: true,
    installed: true,
    permissions: {
      filesystem: "read",
      network: false,
      shell: false,
      external_directory: false,
      secrets: false,
    },
    tags: ["主控", "调度"],
  },
  {
    id: "railwise.skill.survey_review",
    kind: "skill",
    name: "复测资料检查",
    description: "检查线路复测资料完整性、缺失文件和交付风险。",
    version: "0.1.0",
    source: "builtin",
    enabled: true,
    installed: true,
    permissions: {
      filesystem: "read",
      network: false,
      shell: false,
      external_directory: false,
      secrets: false,
    },
    tags: ["测绘", "资料检查"],
  },
  {
    id: "railwise.tool.file_reader",
    kind: "tool",
    name: "本地文件读取",
    description: "读取当前工作区内的工程文件。",
    version: "0.1.0",
    source: "builtin",
    enabled: true,
    installed: true,
    permissions: {
      filesystem: "read",
      network: false,
      shell: false,
      external_directory: false,
      secrets: false,
    },
    tags: ["文件", "本地"],
  },
  {
    id: "railwise.workflow.cpiii_resurvey",
    kind: "workflow",
    name: "CPIII 复测预案",
    description: "串联规范查询、复测校核和交付摘要。",
    version: "0.1.0",
    source: "builtin",
    enabled: true,
    installed: true,
    permissions: {
      filesystem: "read",
      network: false,
      shell: false,
      external_directory: false,
      secrets: false,
    },
    tags: ["工作流", "CPIII"],
  },
  {
    id: "railwise.mcp.local_tools",
    kind: "mcp",
    name: "本地工具桥接",
    description: "连接当前工作区允许的本地工具能力。",
    version: "0.1.0",
    source: "builtin",
    enabled: false,
    installed: true,
    permissions: {
      filesystem: "read",
      network: false,
      shell: true,
      external_directory: false,
      secrets: false,
    },
    tags: ["MCP", "本地"],
  },
  {
    id: "railwise.provider.deepseek",
    kind: "provider",
    name: "DeepSeek",
    description: "默认推荐的中文工程任务模型提供方。",
    version: "0.1.0",
    source: "builtin",
    enabled: false,
    installed: true,
    permissions: {
      filesystem: "none",
      network: true,
      shell: false,
      external_directory: false,
      secrets: true,
    },
    tags: ["模型", "推荐"],
  },
]
