import { CapabilityManifest } from "./schema"

export const builtins = CapabilityManifest.array().parse([
  {
    id: "railwise.harness.safe",
    kind: "harness_profile",
    name: "本地安全模式",
    description: "默认要求用户确认写文件、执行命令和访问外部目录。",
    version: "0.1.0",
    source: "builtin",
    enabled: true,
    installed: true,
    permissions: {
      filesystem: "read",
      network: false,
      shell: false,
      external_directory: false,
      secrets: false,
    },
    tags: ["安全", "默认"],
  },
  {
    id: "railwise.agent.chief_manager",
    kind: "agent",
    name: "项目总控",
    description: "理解任务、拆解计划，并调度专业智能体执行。",
    version: "0.1.0",
    source: "builtin",
    enabled: true,
    installed: true,
    permissions: {
      filesystem: "read",
      network: false,
      shell: false,
      external_directory: false,
      secrets: false,
    },
    tags: ["主控", "调度"],
  },
  {
    id: "railwise.agent.cpiii_specialist",
    kind: "agent",
    name: "CPIII 测量专家",
    description: "负责 CPIII 控制网、轨道精调和测量成果复核。",
    version: "0.1.0",
    source: "builtin",
    enabled: true,
    installed: true,
    permissions: {
      filesystem: "read",
      network: false,
      shell: false,
      external_directory: false,
      secrets: false,
    },
    tags: ["测量", "CPIII"],
  },
  {
    id: "railwise.skill.survey_review",
    kind: "skill",
    name: "复测资料检查",
    description: "检查线路复测资料完整性、缺失文件和交付风险。",
    version: "0.1.0",
    source: "builtin",
    enabled: true,
    installed: true,
    permissions: {
      filesystem: "read",
      network: false,
      shell: false,
      external_directory: false,
      secrets: false,
    },
    tags: ["测绘", "资料检查"],
  },
  {
    id: "railwise.skill.report_delivery",
    kind: "skill",
    name: "成果报告交付",
    description: "整理检查结果、技术说明、交付清单和报告草稿。",
    version: "0.1.0",
    source: "builtin",
    enabled: true,
    installed: true,
    permissions: {
      filesystem: "write",
      network: false,
      shell: false,
      external_directory: false,
      secrets: false,
    },
    tags: ["报告", "交付"],
  },
  {
    id: "railwise.tool.file_reader",
    kind: "tool",
    name: "本地文件读取",
    description: "读取当前工作区内的工程文件。",
    version: "0.1.0",
    source: "builtin",
    enabled: true,
    installed: true,
    permissions: {
      filesystem: "read",
      network: false,
      shell: false,
      external_directory: false,
      secrets: false,
    },
    tags: ["文件", "本地"],
  },
  {
    id: "railwise.tool.report_writer",
    kind: "tool",
    name: "报告文件生成",
    description: "在当前工作区生成 Markdown、清单和报告草稿。",
    version: "0.1.0",
    source: "builtin",
    enabled: true,
    installed: true,
    permissions: {
      filesystem: "write",
      network: false,
      shell: false,
      external_directory: false,
      secrets: false,
    },
    tags: ["文件", "报告"],
  },
  {
    id: "railwise.workflow.survey_package_review",
    kind: "workflow",
    name: "复测资料完整性检查",
    description: "从资料目录出发，检查原始数据、成果文件、缺失项和下一步计划。",
    version: "0.1.0",
    source: "builtin",
    enabled: true,
    installed: true,
    permissions: {
      filesystem: "read",
      network: false,
      shell: false,
      external_directory: false,
      secrets: false,
    },
    tags: ["工作流", "复测"],
  },
  {
    id: "railwise.provider.deepseek",
    kind: "provider",
    name: "DeepSeek",
    description: "推荐默认模型提供方，可用于主控和专业智能体。",
    version: "0.1.0",
    source: "builtin",
    enabled: false,
    installed: true,
    permissions: {
      filesystem: "none",
      network: true,
      shell: false,
      external_directory: false,
      secrets: true,
    },
    tags: ["模型", "推荐"],
  },
  {
    id: "railwise.mcp.filesystem",
    kind: "mcp",
    name: "文件系统 MCP",
    description: "面向当前工作区的文件检索与读写连接能力。",
    version: "0.1.0",
    source: "builtin",
    enabled: false,
    installed: true,
    permissions: {
      filesystem: "write",
      network: false,
      shell: false,
      external_directory: true,
      secrets: false,
    },
    tags: ["MCP", "文件"],
  },
])
