import { test, expect, afterEach } from "bun:test"
import { mkdtemp, mkdir, rm } from "fs/promises"
import os from "os"
import path from "path"
import { models, source } from "../../script/models"

const dirs: string[] = []

afterEach(async () => {
  delete process.env.MODELS_DEV_API_JSON
  delete process.env.RAILWISE_MODELS_URL
  await Promise.all(dirs.splice(0).map((dir) => rm(dir, { recursive: true, force: true })))
})

async function dir() {
  const root = await mkdtemp(path.join(os.tmpdir(), "railwise-models-"))
  dirs.push(root)
  await mkdir(path.join(root, "test/tool/fixtures"), { recursive: true })
  return root
}

test("seeds models snapshot from fixture when models.dev is unavailable", async () => {
  const root = await dir()
  const data = '{"provider":{"id":"provider","name":"Provider","env":[],"models":{}}}'
  await Bun.write(path.join(root, "test/tool/fixtures/models-api.json"), data)

  const result = await models(root, async () => {
    throw new Error("offline")
  })

  expect(result).toBe(data)
})

test("reuses existing generated snapshot when models.dev is unavailable", async () => {
  const root = await dir()
  await mkdir(path.join(root, "src/provider"), { recursive: true })
  await Bun.write(path.join(root, "src/provider/models-snapshot.ts"), "export const snapshot = {} as const\n")
  await Bun.write(path.join(root, "test/tool/fixtures/models-api.json"), "{}")

  const result = await models(root, async () => {
    throw new Error("offline")
  })

  expect(result).toBeUndefined()
})

test("generates valid snapshot source from fixture text with trailing newline", () => {
  expect(source('{"provider":{}}\n')).toBe(
    '// Auto-generated by build.ts - do not edit\nexport const snapshot = {"provider":{}} as const\n',
  )
})
